### ISSUE TITLE
Fix content problem on /year/2019/info/papers-sessions.md

### ISSUE THREAD

**Issue by Kaiyiwing** [ieee-vgtc/ieeevis.org#778] opened 2019-08-30 04:09 UTC
The author list of "ShapeWordle: Tailoring Wordles using Shape-aware Archimedean Spirals (J)"
is wrong, the right author list is "Yunhai Wang, Xiaowei Chu, Kaiyi Zhang, Chen Bao, Xiaotong Li, Jian Zhang, Chi-Wing Fu, Christophe Hurter, Oliver Deussen, and Bongshin Lee"

**Comment by yelper** [comment] 2019-09-06 18:43
Duplicate of #782, waiting for confirmation from InfoVis chairs..

**Closed by yelper** 2019-09-06 18:43 UTC
